# Generated by Django 3.0.3 on 2022-10-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_photo', models.ImageField(default='default.jpeg', upload_to='profile_photo')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_photo', models.ImageField(default='default.jpeg', upload_to='profile_photo')),
                ('is_patient', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=10)),
                ('guardian', models.CharField(max_length=255, null=True)),
                ('other_guardian', models.CharField(max_length=255, null=True)),
                ('balance', models.CharField(default='0.00', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='possible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('info', models.TextField(max_length=255)),
                ('self_care', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_body', models.CharField(max_length=255)),
                ('possible_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.possible')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='possible_cause_video')),
                ('possible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.possible')),
            ],
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms_name', models.CharField(max_length=255, unique=True)),
                ('question_id', models.ManyToManyField(to='main_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'approved_doctor'), ('2', 'approved_patient'), ('3', 'aggreed')], max_length=255)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='rating_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.patient')),
            ],
        ),
    ]
