# Generated by Django 3.0.3 on 2022-10-27 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
        ),
        migrations.AlterField(
            model_name='schedule_consultation',
            name='status',
            field=models.CharField(choices=[('1', 'approved_doctor'), ('2', 'approved_patient'), ('3', 'aggreed'), ('4', 'done')], max_length=255),
        ),
    ]
